apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: summonplatforms.summon.ridecell.io
spec:
  group: summon.ridecell.io
  names:
    kind: SummonPlatform
    plural: summonplatforms
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              type: object
            hostname:
              type: string
            pullSecret:
              type: string
            secret:
              type: string
            slackAPIKey:
              type: string
            slackChannelName:
              type: string
            version:
              type: string
          required:
          - version
          - secret
          type: object
        status:
          properties:
            message:
              type: string
            migrateVersion:
              type: string
            notification:
              properties:
                LastErrorHash:
                  type: string
                NotifyVersion:
                  type: string
              type: object
            postgresStatus:
              type: string
            pullSecretStatus:
              type: string
            status:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
