apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: summonplatforms.summon.ridecell.io
spec:
  group: summon.ridecell.io
  names:
    kind: SummonPlatform
    plural: summonplatforms
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            hostname:
              type: string
            secret:
              type: string
            version:
              type: string
          required:
          - version
          - secret
          type: object
        status:
          properties:
            migrateVersion:
              type: string
            postgresStatus:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
