apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: djangousers.summon.ridecell.io
spec:
  group: summon.ridecell.io
  names:
    kind: DjangoUser
    plural: djangousers
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            database:
              properties:
                database:
                  type: string
                host:
                  type: string
                passwordSecretRef:
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                  required:
                  - name
                  - key
                  type: object
                port:
                  format: int64
                  type: integer
                username:
                  type: string
              required:
              - host
              - username
              - passwordSecretRef
              type: object
            passwordSecret:
              type: string
            staff:
              type: boolean
            superuser:
              type: boolean
            username:
              type: string
          required:
          - username
          - database
          - staff
          - superuser
          type: object
        status:
          properties:
            message:
              type: string
            status:
              type: string
          required:
          - status
          - message
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
