version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1
    working_directory: /go/src/github.com/Ridecell/ridecell-operator

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-vendor-{{ checksum "Gopkg.lock" }}
        - v1-vendor

    - run: mkdir /usr/local/kubebuilder
    - run: curl -L https://storage.googleapis.com/kubebuilder-release/kubebuilder_master_darwin_amd64.tar.gz | tar -zxv --strip-components=1 -C /usr/local/kubebuilder
    - run: go get -u github.com/onsi/ginkgo/ginkgo
    - run: dep ensure
    - run: make test

    - save_cache:
        key: v1-vendor-{{ checksum "Gopkg.lock" }}
        paths:
        - vendor/
