version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1
    #- image: rabbitmq:3-management
    working_directory: /go/src/github.com/Ridecell/ridecell-operator
    environment:
      RABBITMQ_HOST_DEV: http://localhost:15672
      RABBITMQ_SUPERUSER: guest
      RABBITMQ_SUPERUSER_PASSWORD: guest

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-vendor-{{ checksum "Gopkg.lock" }}
        - v1-vendor
    - run: echo "export RAND_OWNER_PREFIX=$(head -c 512 /dev/urandom | tr -dc 'a-z0-9' | head -c 8)" >> $BASH_ENV
    - run: sudo mkdir /usr/local/kubebuilder/
    - run: curl -L https://storage.googleapis.com/kubebuilder-release/kubebuilder_master_linux_amd64.tar.gz | sudo tar -zxv --strip-components=1 -C /usr/local/kubebuilder/
    #- run: curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.8/kubebuilder_1.0.8_linux_amd64.tar.gz | sudo tar -zxv --strip-components=1 -C /usr/local/kubebuilder/
    - run: make dep test
    - run: goveralls -coverprofile=gover.coverprofile -service=circle-ci -repotoken=$COVERALLS_TOKEN
    - run:
        command: go run scripts/aws_cleanup/delete_operator_resources.go
        when: always
    - run: mkdir workspace && cp -r config/crds workspace/crds
    - persist_to_workspace:
        root: workspace
        paths:
        - crds

    - save_cache:
        key: v1-vendor-{{ checksum "Gopkg.lock" }}
        paths:
        - vendor/
  build:
    docker:
    - image: us.gcr.io/ridecell-public/docker-gcloud:2018-09-17
    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: workspace
    - run: docker build -t us.gcr.io/ridecell-1/ridecell-operator:${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}-${CIRCLE_BRANCH} .
    - run: echo ${GCP_SERVICE_ACCOUNT} > gcp-key.json
    - run: gcloud auth activate-service-account --key-file gcp-key.json
    - run: gcloud --quiet config set project ridecell-1
    - run: gcloud auth configure-docker
    - run: docker push us.gcr.io/ridecell-1/ridecell-operator:${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}-${CIRCLE_BRANCH}
    - run: echo ${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}-${CIRCLE_BRANCH} > workspace/tag
    - persist_to_workspace:
        root: workspace
        paths:
        - tag
  deploy:
    docker:
    - image: us.gcr.io/ridecell-public/helm-gcloud:2.8.2
    steps:
    - checkout
    - attach_workspace:
        at: workspace
    - run: echo ${GCP_SERVICE_ACCOUNT_SANDBOX} > gcp-key.json
    - run: gcloud auth activate-service-account --key-file gcp-key.json
    - run: gcloud --quiet config set project ridecell-sandbox
    - run: gcloud container clusters get-credentials noah-test --region=us-west1
    - run: cp workspace/crds/* helm/templates/crds/
    - run: helm upgrade --install --namespace ridecell-operator --set tag=$(cat workspace/tag) ridecell-operator ./helm

workflows:
  version: 2
  default:
    jobs:
    - test
    - build:
        requires:
        - test
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
