apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: pullsecrets.secrets.ridecell.io
spec:
  group: secrets.ridecell.io
  names:
    kind: PullSecret
    plural: pullsecrets
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            pullSecretName:
              description: 'Important: Run "make" to regenerate code after modifying
                this file Name of the secret to use for image pulls. Defaults to `"pull-secret"`.'
              type: string
          type: object
        status:
          properties:
            message:
              description: Message related to the current status.
              type: string
            status:
              description: Overall object status
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
