name = "webui"
bin = "bin/webui"
vcs = "none"
with_pop = false
with_sqlite = false
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = false
with_docker = false
with_grifts = false
as_web = true
as_api = false
